export const roomColors = [
  'bg-blue-500',
  'bg-green-500',
  'bg-purple-500',
  'bg-yellow-500',
  'bg-pink-500',
  'bg-teal-500',
  'bg-indigo-500'
];

export const operationData: Record<string, string[]> = {
  "Cataract Surgeries": [
    "cataract extraction",
    "cataract extraction and sclera fixation IOL",
    "Phacoemulsification & Foldable IOL implantation",
    "Secondary IOL implantatation",
    "cataract extraction and IOL implantation+Subscleral trabeculectomy",
    "cataract extraction and IOL implantation",
    "after cataract aspiration",
    "Lensectomy for subluxated lens",
    "phaco trabeculectomy +pciol implantation",
    "Phacoemulsification"
  ],
  "Retina and Vitreous Surgeries": [
    "removal of infected buckle",
    "Vitrectomy",
    "cataract extraction and IOL implantation,and Vitrectomy+ silicone oil injection",
    "Silicone oil removal and scleral fixation of IOL",
    "Vitrectomy and FB extraction",
    "Silicone bubble in anterior chamber",
    "Phacoemulsification +PCIOL+ Silicone oil removal",
    "Phacoemulsification + Silicone oil removal",
    "cataract extraction + Vitrectomy",
    "IOL explantation + Vitrectomy +IOL implantation",
    "Silicon oil removal+retinopexy+silicon oil injection",
    "Pars plana vitrectomy + iol implantation",
    "cataract extraction and IOL implantation,and +silicone oil removal+retinopexy+ silicone oil injection",
    "retinopexy+ silicon oil injection",
    "Retinopexy +removal of retinal traction+silicon oil injection",
    "Retinopexy",
    "Cataract extraction and IOL implantation and silicon oil removal and silicon oil injectione",
    "Phacoemulsification + silicone oil removal + retinopexy+ silicone oil injection",
    "cataract extraction+vitrectomy+silicon oil injection",
    "Vitrectomy +retinopexy +gas injection",
    "Vitrectomy +endo laser+ silicone oil injection",
    "laser coagulation of avascular retina by laser indirect ophthalmoscopy",
    "Retinopexy + Vitrectomy + silicone oil injection",
    "cataract extraction and IOL implantation,and Vitrectomy",
    "Silicone oil removal"
  ],
  "Orbital Surgeries": [
    "Dacryocystectomy",
    "enuclation and mid pore implantation",
    "contracted socket repair with midpore implant",
    "silicone intubation",
    "repair of arbital floor fracture +tytanium mesh",
    "blepharoplasty",
    "corneal and conjunctival amniotic membrane graft",
    "evisceration",
    "Conjunctival graft",
    "Orbital volume augmentation",
    "Recurrent pterygium",
    "Endoscopic DCR",
    "orbital biopsy",
    "DCR",
    "Reconstruction of lid after removal of tumor",
    "Enucleation",
    "midpore implant",
    "Repair of orbital floor fracture",
    "Ptosis repair (blepharoplasty",
    "Lid lesion excision and blepharoplasty",
    "Contracted Socket repair",
    "Blepharoplasty with Metero tube",
    "Upper lid blepharoplasty with silicone stent",
    "Orbitotomy & tumer excision"
  ],
  "Strabismus Surgeries": [
    "Strabismus Surgery"
  ],
  "Corneal Surgeries": [
    "keratoplasty",
    "keratoplasty + cataract extraction and IOL implantation",
    "corneal cross linking",
    "Keratoplasty+ cataract extraction",
    "chelation of band shaped keratopathy",
    "Corneal tumor excision"
  ],
  "Glaucoma Surgeries": [
    "Subscleral trabeculectomy + Mitomycin c",
    "Subscleral trabeculectomy + ologen implant",
    "Subscleral trabeculectomy",
    "Ahmed valve implant",
    "Subscleral trabeculectomy + Mitomycin c & ologen implant",
    "Combined subscleral trabeculectomy & trabeculotomy",
    "Diode laser cyclophotocoagulation",
    "Ahmed Valve repositioning"
  ],
  "Injection Procedures": [
    "intra- vitreal injection of stercid (Triamcinolone Acetate)",
    "intra- vitreal injection of anti-vegf (Lucentis)",
    "Phacoemulsification + PCIOL + intra- vitreal injection of anti-vegf (Lucentis)",
    "Ozordix",
    "Eylea",
    "gas injection",
    "Subconjunctival injection of corticosteroid",
    "intra- vitreal injection of anti-vegf"
  ],
  "Other Surgeries": [
    "Anterior vitrectomy",
    "ACIOL implantation",
    "Iris claw iol implantation",
    "Repositioning of iol",
    "iol explantation",
    "Lens matter aspiration",
    "Wash of anterior chamber",
    "keratectomy",
    "Anterior vitrectomy +IOL repositioning",
    "Secondary IOL implantation ( scleral fixation)",
    "Lensectomy ,anterior vitrectomy and scleral fixation of IOL",
    "Peripheral iridectomy",
    "IOL extraction",
    "Recurrent pterygium",
    "Excision of recurrent ptrygium with conjunctival autograft",
    "secondary IOL implantation through Iris fixation",
    "surgical posterior capsulotomy",
    "iol exchange",
    "Iris repair",
    "pupilloplasty"
  ],
  "Trauma Surgeries": [
    "Corneal and sclera wound repair",
    "Upper lid wound repair",
    "Lower lid wound repair",
    "Upper lid wound repair including margin",
    "Lower lid wound repair including margin",
    "Upper lid wound repair including margin and canaliculus",
    "Lower lid wound repair including margin and canaliculus",
    "Corneal and sclera wound repair with cataract extraction",
    "Hyphema aspiration",
    "Repair of gapped corneal section",
    "Repair of gapped corneal section and reposition of iris",
    "Repair of gapped corneal section , reposition of iris and anterior vitrectomy",
    "Repair of gapped corneal section and anterior vitrectomy",
    "IOFB magnet extraction",
    "intra- vitreal injection of antibiotic"
  ],
  "Minor Surgeries": [
    "cryoabblation",
    "Silicone tube removal",
    "dermato chalasis",
    "Intra lesional injection of kenacort",
    "Subconjunctival injection",
    "Conjunctival suture removal",
    "PTS removal",
    "abscess evacuation",
    "Stye excision",
    "chalazion excision",
    "Examined under a general anesthetic",
    "Electrolysis of rubbing lashes",
    "Pterygium excision",
    "Lacrimal passage probing",
    "entropion",
    "ectropion",
    "Theraputic contact lens",
    "Cyclocryotherapy",
    "Cautery of Corneal ulcer",
    "Repair of Cojunctival wound",
    "Evisceration or Enucleation",
    "corneal suture removal",
    "Cojunctival nevus excision",
    "Cojunctival tumor excision",
    "Symblepharon excision",
    "Corneal tumor excision",
    "Repair of eye lid wound",
    "Orbital hemorrhage evacuation",
    "Trichiasis repair",
    "conjunctival cyst excision",
    "Skin papilloma excision",
    "Xanthelasma excisin",
    "skin sutures removal",
    "for artifial eye",
    "corneal F B removal"
  ],
  "Pediatric Surgeries": [
    "IOL explantation + surgical capsulotomy",
    "Foldable iol implantation",
    "Endo LASER surgery for neonate",
    "surgical posterior capsulorhexis, anterior vitrectomy and foldable IOL implantation",
    "phacoaspiration + anterior vitrectomy",
    "phacoaspiration + iol implantation + anterior vitrectomy",
    "Phacoasipration+PCIOL",
    "Phacoaspiration, posterior capsulorhexis, anterior vitrectomy and foldable IOL implantation",
    "Phacoaspiration and posterior capsulorhexis and anterior vitrectomy",
    "Surgical capsulotomy + iol exchange",
    "Secondary iol implantation,anterior vitrectomy and pupiloplasty"
  ]
};

export const operationCollections = Object.keys(operationData);

export const surgeons = [
  "أ.د/ آمال أحمد عبد الوهاب",
  "أ.د/ أحمد رشيد سامح محمود اللقاني",
  "أ.د/ أحمد سامي الوهيدى الحسيني",
  "أ.د/ أحمد مصطفى إسماعيل",
  "أ.د/ أسعد أحمد ابراهيم غانم",
  "أ.د/ أشرف إبراهيم معوض محمد",
  "أ.د/ أشرف محمد سويلم محمد",
  "أ.د/ أمل مصطفى البندارى زغبي",
  "أ.د/ أيهاب حسن احمد نعمة الله",
  "أ.د/ إجلال محمد السعيد مصطفى",
  "أ.د/ ابراهيم طه العدوى عفصه",
  "أ.د/ اماني السيد بدوي محمد",
  "أ.د/ ايمان عزمي عبد الحميد عوض",
  "أ.د/ ايمان محمد الحفنى عطا",
  "أ.د/ ايمن السيد عبد الغفار محمد",
  "أ.د/ ايهاب محمد عبد الحميد نافع",
  "أ.د/ حاتم السعيد العوضي",
  "أ.د/ حسام الدين طه زينهم",
  "أ.د/ حسام الدين يوسف عمر ابو الخير",
  "أ.د/ حسام محمد على السيد الفلال",
  "أ.د/ حمزة عبد الحميد أحمد عبد الله",
  "أ.د/ داليا صبرى الإمام",
  "أ.د/ رءوف أمين أحمد النفيس",
  "أ.د/ رانيا كامل عبد الحميد فرج",
  "أ.د/ سامح محمود حسن صالح",
  "أ.د/ سامي على محمد أبو الخير",
  "أ.د/ سحر مصطفي الطرشوبي",
  "أ.د/ شريف السعيد الخولى",
  "أ.د/ شــرين محمود عبدالسلام هجرس",
  "أ.د/ طارق احمد عبد الوهاب محسن",
  "أ.د/ طاهر محمد جمال الدين الدسوقي",
  "أ.د/ عادل السيد عبد العال اللايح",
  "أ.د/ عبير محمد صادق خطاب",
  "أ.د/ عصام عبد الحميد السعيد بدور",
  "أ.د/ عمرو محمد حسن القنيشي",
  "أ.د/ ماجدة عبد الواحد التركي",
  "أ.د/ محمد أحمد محمد خلف",
  "أ.د/ محمد عبد الله جاد",
  "أ.د/ محمد ممدوح صابر علوان",
  "أ.د/ محمد نادر رشدي المتولي",
  "أ.د/ محمد هاني عبد الرحمن سالم",
  "أ.د/ منال على حسين إبراهيم",
  "أ.د/ منى عبد القادر رمضان",
  "أ.د/ مها محمد عثمان شاهين",
  "أ.د/ نشأت شوقي زكى",
  "أ.د/ هانم محمد عبد الفتاح كشك",
  "أ.د/ هشام إبراهيم علي السروجي",
  "أ.د/ وليد علي مصطفي أبو سمره",
  "أ.د/ وليد محمد عبد العزيز جعفر"
];

export const assistants = [
  "ط/ آلاء أحمد عبد الهادى أبو النجا",
  "ط/ آيه اسماعيل عبد العال سلطان",
  "ط/ آيه عماد الدين مصطفى مصطفى",
  "ط/ أيه صبرى محمد جمعه",
  "ط/ أحمد سمير محمد محمد عسيلى",
  "ط/ أحمد صالح أحمد محمد",
  "ط/ أحمد عامر عبد الله",
  "ط/ أحمد عبد المجيد حسين نصر",
  "ط/ أحمد محمد محمد الشيمى",
  "ط/ أحمـــد محمـــود هـــلال فرج",
  "ط/ احمد سامي علي ابو الخير",
  "ط/ احمد محمد علي الجبوري",
  "ط/ احمد نشات فضل شرف الدين",
  "ط/ أسامة ابراهيم العدوى",
  "ط/ أمانى السيد أحمد محمد",
  "ط/ أميرة أحمد السيد مؤنس",
  "ط/ أميرة أسامة عبد المقصود أحمد",
  "ط/ أميرة محمود بدر الدياسطى",
  "ط/ إسراء عبد السلام محمد جاد",
  "ط/ اريج تيسير نظيف عبدو",
  "ط/ اسلام مدحت رزق",
  "ط/ امل نبيل محمود المهدي",
  "ط/ امنية أحمد الجزار",
  "ط/ امنية سالم",
  "ط/ انجي عمرو حسين الغول",
  "ط/ اهداء محمد فتحي",
  "ط/ ايمان السيد محمود طافور",
  "ط/ ايمان جمال مجاهد",
  "ط/ ايمان سامي",
  "ط/ ايمان سمير احمد عبد الحليم",
  "ط/ ايمان صلاح أحمد البرعى",
  "ط/ ايمن محمد مجلى على",
  "ط/ بنان الصاوي",
  "ط/ تامر محمد بدير",
  "ط/ حسن عثمان",
  "ط/ حنان أحمد السيد ماضي",
  "ط/ خالد مصطفى السعيد",
  "ط/ داليا سمير حامد زقزوق",
  "ط/ دعاء عزت عبد الله محمود",
  "ط/ رؤي فيصل بحبوح",
  "ط/ رحمه أيمن أحمد عبد العزيز",
  "ط/ رغد يوسف حبال",
  "ط/ زيدون احمد جوهر امين",
  "ط/ سارة كامل",
  "ط/ ساره شفيق",
  "ط/ ساره عبد الناصر فتوح ابراهيم",
  "ط/ سالى جمال محمد عماره",
  "ط/ سامي رضوان",
  "ط/ سلمى عادل ابراهيم عبده",
  "ط/ سلمى عثمان السيد سليمان",
  "ط/ سلمي محمود منصور احمد",
  "ط/ سمر عبد الشافى محمد بدر",
  "ط/ شمس عصام ذكى ابراهيم",
  "ط/ شيرين خالد على المتولى",
  "ط/ ضياء نصر منصور نصر",
  "ط/ طاهر علي طاهر",
  "ط/ عبد الرحمن السيد أحمد أبو فوده",
  "ط/ عبد الرحمن حسن قطب قطب",
  "ط/ عبد العزيز على عبد العزيز شقير",
  "ط/ عبد الله السيد عبد الله",
  "ط/ عبد الله سامي عبد الله العجه",
  "ط/ عزة احمد جمال الدين الشاذلي",
  "ط/ علا الملاح",
  "ط/ علا شها",
  "ط/ علياء ايمن ابراهيم الدسوقى",
  "ط/ عمر هشام ابراهيم السروجي",
  "ط/ عمرو محمد محمود طايل",
  "ط/ غاده طه حسن العلاوى",
  "ط/ فاطمة عبد العزيز سعدشتا",
  "ط/ فاطمة مختار الطاهر",
  "ط/ فيرنا عادل ونيس المنياوى",
  "ط/ كمال عيسى علي",
  "ط/ مايكل مدحت ميخائيل مسيحه",
  "ط/ محمد احمد حبيب حسن",
  "ط/ محمد ايهاب محمد نافع",
  "ط/ محمد رضا ابو النجا احمد",
  "ط/ محمد علي عبد الله عبد الله",
  "ط/ مريم طاهر عقل",
  "ط/ مصطفي احمد سامي الوهيدي",
  "ط/ نجوى حسين عبد المجيد",
  "ط/ ندى جمال محمود محمد",
  "ط/ ندى عبد الرحمن على صادق",
  "ط/ ندى مصطفى بدير الخولى",
  "ط/ نديم حسام قاسم العبادله",
  "ط/ نوار اسعد حاطوم",
  "ط/ هاجر خيري",
  "ط/ هدير السيد",
  "ط/ ولاء وائل",
  "ط/ يارا نبيل مصطفى ابراهيم"
];

export const visualAcuityOptions = [
  "6/6", "6/9", "6/12", "6/18", "6/24", "6/36", "6/60",
  "5/60", "4/60", "3/60", "2/60", "1/60",
  "CF 75 cm", "CF 50 cm", "CF 25 cm",
  "HM", "PL", "No PL", "can't be assessed"
];
